# Generated by Django 3.1.5 on 2023-10-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20231020_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
