# Generated by Django 3.1.5 on 2023-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20231020_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
