# Generated by Django 3.1.5 on 2023-10-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20231025_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(default='f6ff0a', editable=False, max_length=220, unique=True),
        ),
    ]
